### PR TITLE
Implemented rabin-miller prime test.

### PR DESCRIPTION
**Pull request by Xaltonon**
This greatly improves the efficiency of is_prime_optimal for large
numbers.

### CODE REVIEW

**Comment by mingrammer** [comment]
Did it tested with `n=1`?

**Comment by Xaltonon** [comment]
Fixed that, woops.

**Comment by mingrammer** [comment]
There is an problem. The `877` is a prime, but your script decide it as non-prime. 

You should run `python3 -m doctest prime/is_prime_optimal.py -v` before commit.

**Comment by Xaltonon** [comment]
Merge conflict was preventing it from working, everything checks out now.

**Comment by mingrammer** [comment]
Ye, I've refactored some codes for clean, so, you  should .. reflect these changes to your works. (Sorry for conflicting)

**Comment by Xaltonon** [comment]
This could probably be merged now.

**Comment by mingrammer** [comment]
@Xaltonon Yes, the travis CI tests was all passed successfully. Thanks for contributing :)

**Comment by mingrammer** [comment]
I added you on `README.md` as contributor. :heart:

**Pull request merged**
