### PR TITLE
Added next_prime function

### PR DESCRIPTION
**Pull request by TsimpDim**
On my way across ProjectEuler I wrote this function and thought it would be useful to your project. I avoided using an is_prime() function so it is indepedent althought such a function would definitely make the code shorter.

### CODE REVIEW

**Comment by mingrammer** [comment]
Hi @TsimpDim Thanks for contributing :)

That's good one, but I have a suggestion. Would you use the `""" ... """` form for function docstring? It is just for consistence with other codes! See [this example](https://github.com/mingrammer/funmath/blob/master/prime/is_prime.py).

And, it is better to clean up the spaces or line spaces!

You could also add the function on `prime` section of `README.md`

**Comment by TsimpDim** [comment]
Not sure why the check failed

**Comment by mingrammer** [comment]
You can check the failing case by running `python3 -m doctest next_prime.py -v`

**Comment by TsimpDim** [comment]
Done

**Comment by mingrammer** [comment]
Thanks you @TsimpDim for contributing :)

**Comment by mingrammer** [comment]
I added you as a contributor on `README.md`

**Pull request merged**
